export const projects = [
  {
    title: 'Loom-Recorder Clone',
    description: "I re-created the frontend of Loom screen recorder official website. I got attracted to their beautiful UI. It was a great experience for me to build the frontend.",
      image: '/images/loom.jpeg',
      tags: ['Next', 'Tailwind'],
    source: 'https://llum.netlify.app',
    visit: 'https://github.com/encode412/toom',
    id: 0,
  },
  // {
  //   title: 'E-Commerce',
  //   description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
  //   image: '/images/2.png',
  //   tags: ['React', 'JavaScript'],
  //   source: 'https://google.com',
  //   visit: 'https://royalstemplate.netlify.app',
  //   id: 1,
  // },
  {
    title: 'Royals Template', 
    description: "Royals is a web template i created targeting the resturant and food industry, which anyone can use to present their own business online.",
      image: '/images/royals.jpeg',
      tags: ['React', 'CSS'],
    source: 'https://royalstemplate.netlify.app',
    visit: 'https://github.com/encode412/royals_template',
    id: 2,
  },
  {
    title: 'GeniusTutors',
    description: "This is a landing page I created for an Educational agency to showcase their acheivements and available classes.",
    image: '/images/genius.jpeg',
    tags: ['HTML', 'CSS', 'AOS library'],
    source: 'https://geniustutorsacademy.netlify.app/',
    visit: 'https://github.com/encode412/Geniustutors',
    id: 3,
  },
  {
    title: 'TravelToday',
    description: "This is a web template I created targeting the travel industry to showcase their services and more.",
    image: '/images/travel.jpeg',
    tags: ['HTML', 'CSS'],
    source: 'https://traveltoday.netlify.app/',
    visit: 'https://github.com/encode412/Geniustutors',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2022, text: 'Worked as a developer intern', },
  { year: 2023, text: 'Worked as a Frontend Instructor', },
  { year: 2023, text: 'Joined a company as a frontend developer', },
  // { year: 2021, text: 'Started my own platform', },
];